services:
  - type: web
    name: sql-library-manager
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: library_db
          property: connectionString

databases:
  - name: library_db
    databaseName: library
    user: library_user
